#! /usr/bin/env bash

# Idempotent bootstrap script to stand up a new development Mac
#
# Usage: bootstrap <apple id> <apple id pass>
#
# Note: If you prefix a bash command with a space it will not be saved to your
# command history.
#
# Subsequent runs will ensure packages are up-to-date.

# Abort this script if any command fails
set -e

# Set the computer name to
# COMPUTER_NAME='Apollo-15'

# Toggle to configure server or desktop
STRAPPING_SERVER=true

PATH="/usr/local/bin:$PATH"

# Some helper functions used throughout the script
silently() {
  $* >/dev/null 2>&1
}

ignore_error() {
  $* || echo -n
}

add_assitive_device() {
  sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAccessibility','$1',1,1,1,NULL);"
}

remove_assitive_device() {
  sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "DELETE FROM access WHERE client='$1';"
}

install_mas_app() {
  if [ ! -x "/Applications/$2.app" ]; then
    echo "-----> Installing $2 from Mac App Store: http://itunes.apple.com/app/$1"
    add_assitive_device /usr/libexec/sshd-keygen-wrapper
    osascript install_mas_app.scpt $APPLE_ID_USER $APPLE_ID_PASS $1
    remove_assitive_device /usr/libexec/sshd-keygen-wrapper
    silently ignore_error sudo killall "App Store"
  else
    echo "-----> Ensuring $2 still installed from Mac App Store: http://itunes.apple.com/app/$1"
  fi
}

install_cask_app() {
  echo "-----> Installing $1 from Caskroom"
  (silently brew cask ls $1) || brew cask install $1
}

start_service() {
  ignore_error sudo launchctl load -w $1 2> >(grep -v "Operation already in progress")
}

brew_install() {
  echo -n "$1 "
  [[ -n $(brew ls --versions $1) ]] || brew install $1
}

brew_tap() {
  if [[ -z $(brew tap | grep -E "^$1$") ]]; then
    echo "-----> Tapping $1"
    brew tap $1
  fi
}

# Assign apple user/pass from remote variables. (used in conjunction with bootstrap_remote)
if [ -n "$APPLE_ID_USER_REMOTE" ] || [ -n "$APPLE_ID_PASS_REMOTE" ]; then
  APPLE_ID_USER=$APPLE_ID_USER_REMOTE
  APPLE_ID_PASS=$APPLE_ID_PASS_REMOTE
fi

if [ -z "$APPLE_ID_USER" ] || [ -z "$APPLE_ID_PASS" ]; then
  echo '$APPLE_ID_USER and/or $APPLE_ID_PASS missing. Exiting...'
  exit 1
fi

# Don't require a password for sudo. Comment this out if you want it to prompt for a password.
if [[ -z $(sudo grep "$USER.*NOPASSWD" /etc/sudoers) ]]; then
  echo "-----> Adding $USER to NOPASSWD sudoers"
  echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers > /dev/null
fi

if [ -n "$COMPUTER_NAME" ]; then
  echo "-----> Setting computer name to $COMPTUER_NAME"
  sudo scutil --set ComputerName $COMPUTER_NAME
  sudo scutil --set HostName $COMPUTER_NAME
  sudo scutil --set LocalHostName $COMPUTER_NAME
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $COMPUTER_NAME
fi

echo "-----> Create ~/Code directory"
mkdir -p ~/Code

echo "-----> Enabling firewall"
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1

echo "-----> Enabling file sharing (afp), screen sharing (vnc) and remote login (ssh)"
sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
start_service /System/Library/LaunchDaemons/com.apple.screensharing.plist
sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.AppleFileServer -dict Disabled -bool false
start_service /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist
silently ignore_error sudo systemsetup -setremotelogin on

echo "-----> Turn on system updates"
sudo defaults write /Library/Preferences/com.apple.commerce AutoUpdate -bool TRUE
sudo defaults write /Library/Preferences/com.apple.commerce AutoUpdateRestartRequired -bool TRUE
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

if [ "$STRAPPING_SERVER" = true ] ; then
  echo "-----> Disabling screen saver and sleepiness"
  defaults -currentHost write com.apple.screensaver idleTime 0
  sudo pmset sleep 0
  sudo pmset disksleep 0
  sudo pmset autorestart 1
  sudo pmset repeat wakeorpoweron MTWRFSU 5:00:00

  echo "-----> Disabling screen lock"
  defaults -currentHost write com.apple.screensaver askForPassword -int 0

  echo "-----> Disabling IR receiver"
  sudo defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -bool false
  echo "-----> Disabling power button from sleeping system"
  defaults write com.apple.loginwindow PowerButtonSleepsSystem -bool no
fi

#TODO: Make Capslock press Ctrl

echo "-----> Make mouse and keyboard faster"
defaults write NSGlobalDomain KeyRepeat -int 0
defaults write NSGlobalDomain com.apple.mouse.scaling -float 9
defaults write NSGlobalDomain com.apple.trackpad.scaling -int 9
defaults write NSGlobalDomain com.apple.scrollwheel.scaling -float 3

echo "-----> Restart automatically if the computer freezes"
sudo systemsetup -setrestartfreeze on

echo "-----> Enable full keyboard access for all controls (in Keyboard pref pane)"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

echo "-----> Use scroll gesture with the Ctrl (^) modifier key to zoom"
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

echo "-----> Customize dock: Automatically hide the Dock, remove delays"
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0

echo "-----> Tweak Finder: Empty trash securely and without prompt, use column view, enable airdrop over ethernet"
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
defaults write com.apple.finder WarnOnEmptyTrash -bool false
defaults write com.apple.finder EmptyTrashSecurely -bool true
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable disk image verification of dmgs
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

echo "-----> Customize Safari: Add full url in search bar, developer menu, tab highlights each item"
# Show the full URL in the address bar (note: this still hides the scheme)
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Press Tab to highlight each item on a web page
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

echo "-----> Updating system software"
sudo softwareupdate --install --all 2> >(grep -v "No updates are available") 1> /dev/null

echo "-----> Install xcode"
install_mas_app id497799835 Xcode

# FIXME: License acceptance doesn't seem to be typing "agree" correctly
echo "-----> Accepting Xcode Licenses"
./xcode_agree.sh 1> /dev/null

if [ ! -x /usr/local/bin/brew ]; then
  echo "-----> Installing homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "-----> Updating homebrew"
  brew update > /dev/null
  brew upgrade
fi

# Allow installation of more recent versions of some OS X tools
brew_tap homebrew/dupes

echo "-----> Installing Caskroom for installing GUI apps via brew"
silently brew install caskroom/cask/brew-cask

#TODO: Detect if iCloud already logged in and skip
#echo "-----> Configuring iCloud account for $APPLE_ID_USER"
# add_assitive_device /usr/libexec/sshd-keygen-wrapper
# osascript log_in_to_icloud.scpt $APPLE_ID_USER $APPLE_ID_PASS
# remove_assitive_device /usr/libexec/sshd-keygen-wrapper

# Install mac app store and brew cask apps
install_mas_app id425264550 "Blackmagic Disk Speed Test"
install_cask_app carbon-copy-cloner
install_cask_app google-chrome

# Any app you haven't purchase will cause this script to stop
install_mas_app id443987910 1Password
install_mas_app id413857545 Divvy
install_mas_app id623795237 Ulysses
install_mas_app id880001334 Reeder
install_mas_app id411643860 DaisyDisk
install_mas_app id458034879 Dash
install_mas_app id407963104 Pixelmator
install_mas_app id432027450 RadarScope
install_mas_app id557168941 Tweetbot
install_mas_app id715768417 "Microsoft Remote Desktop"
install_mas_app id852320343 Sketch
install_cask_app alfred
install_cask_app mailbox
install_cask_app slack
install_cask_app postico
install_cask_app league-of-legends
install_cask_app transmit

#TODO: Customize dock icons and folders with dockutils
#TODO: Turn off iTunes track notifications
#TODO: Add apps to login items: com.apple.loginitems.plist
#TODO: Configure Terminal.app via plist

echo -n "-----> Installing useful binaries: "

brew_install coreutils                  # GNU core utilities (those that come with OS X are outdated)
brew_install ctags                      # For indexing files (vim tab completion of methods, classes, variables)
brew_install dockutil                   # For adding and removing dock icons
brew_install gcal                       # GNU cal with 3-month view (gcal .)
brew_install git                        # Distributed version control
brew_install git-extras                 # Helpful git commands; See https://github.com/visionmedia/git-extras
brew_install heroku-toolbelt            # Recommened way to install heroku command line
brew_install htop-osx                   # Better top
brew_install macvim --override-system-vim --force # Newer, better, faster, stronger vim
brew_install memcached                  # Good open source memory store for caching
brew_install node                       # JS V8 engine
brew_install phantomjs                  # Headless webkit used for testing (with capybara/poltergeist)
brew_install postgresql --no-python     # Realational Database
brew_install reattach-to-user-namespace # Reattaches user namespace in tmux  (for pasteboard interaction and ruby motion)
brew_install redis                      # Key-value store
brew_install rename                     # Like mv but better (takes regex)
brew_install ruby                       # Straight up Ruby 2.2. Nothing fancy like rbenv or rvm.
brew_install the_silver_searcher        # The Silver Searcher - faster than grep or ack
brew_install tmux                       # Terminal multiplexer (for saving project state and switching between projects)
brew_install tree                       # ASCII view of directory/file structure
brew_install watch                      # Repeateadly run a command (clearing output between runs)
brew_install zsh                        # Zsh 5
echo

echo "-----> All done. Enjoy your shiny new $COMPUTER_NAME."
